--------------------------------------------------------
--  DDL for Table TBLADMIN
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLADMIN" 
   (	"SEQ" NUMBER, 
	"ADMIN_ID" VARCHAR2(40 BYTE), 
	"ADMIN_PW" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLBLACK
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLBLACK" 
   (	"SEQ" NUMBER, 
	"MEMBER_SEQ" NUMBER, 
	"BLACK_YEAR" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLBOOK
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLBOOK" 
   (	"SEQ" NUMBER, 
	"BOOK_NAME" VARCHAR2(100 BYTE), 
	"PUBLISHER" VARCHAR2(100 BYTE), 
	"AUTHOR" VARCHAR2(100 BYTE), 
	"DECIMAL_NUM" NUMBER, 
	"SERIES_NUM" NUMBER, 
	"DELETE_EXIST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLBOOKSTATE
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLBOOKSTATE" 
   (	"BOOK_CODE" VARCHAR2(100 BYTE), 
	"BOOK_SEQ" NUMBER, 
	"BOOK_LOCATION" VARCHAR2(10 BYTE), 
	"DELETE_EXIST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLDECIMALCATEGORY
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLDECIMALCATEGORY" 
   (	"NUM" NUMBER, 
	"DECIMALCODE" VARCHAR2(3 BYTE), 
	"ITEM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLMEMBER
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLMEMBER" 
   (	"SEQ" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"SSN" VARCHAR2(15 BYTE), 
	"WITHDRAWAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLRENT
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLRENT" 
   (	"SEQ" NUMBER, 
	"MEMBER_SEQ" NUMBER, 
	"BOOK_CODE" VARCHAR2(100 BYTE), 
	"RENT_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"EXTENSION_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLRESERVATION
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLRESERVATION" 
   (	"SEQ" NUMBER, 
	"MEMBER_SEQ" NUMBER, 
	"BOOK_SEQ" NUMBER, 
	"RES_DATE" DATE, 
	"DELETE_EXIST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBLSUGGESTIONS
--------------------------------------------------------

  CREATE TABLE "LMS"."TBLSUGGESTIONS" 
   (	"SEQ" NUMBER, 
	"MEMBER_SEQ" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"SUG_CONTENTS" VARCHAR2(4000 BYTE), 
	"REGDATE" DATE, 
	"ANSWER" VARCHAR2(4000 BYTE), 
	"DELETE_SUG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
